/* generated by tools/gen_box.py; do not edit */
#ifndef SBK_UI_BOX_H
#define SBK_UI_BOX_H

/* Hand-drawn box fronts, 256x358 RGBA8.  A game with no picture here
 * gets one composed from its own title logo instead. */

#endif
