key: lindas_castle
enum: LINDAS_CASTLE
legacy_id: 5
kind: standard
behavior: lindas_castle
assets:
  display_lists:
    symbol: LINDAS_CASTLE_COURSE_DISPLAY_LISTS
    decompressed_size: '0x0'
  model_resources:
    symbol: LINDAS_CASTLE_COURSE_MODEL_RESOURCES
    decompressed_size: '0x21480'
  track_mesh:
    symbol: LINDAS_CASTLE_COURSE_TRACK_SECTOR_MESH
    decompressed_size: '0x3F92'
  texture_table:
    symbol: LINDAS_CASTLE_COURSE_TEXTURE_TABLE
    decompressed_size: '0x1528'
  gold_coins:
    symbol: LINDAS_CASTLE_GOLD_COIN_DATA
    decompressed_size: '0x3A0'
  item_boxes:
    symbol: LINDAS_CASTLE_ITEM_BOX_DATA
    decompressed_size: '0x100'
  scene_animation:
    symbol: LINDAS_CASTLE_SCENE_ANIMATION_DATA
    decompressed_size: '0x270'
    legacy_slot: 6
environment:
  lift_entry_position:
  - '0x3D070980'
  - '0x00025DA4'
  course_start_position:
  - '0xFFC990D9'
  - '0x300FA11C'
  - '0x30551EA4'
  lift_entry_yaw_offset: '0x0000'
  light_colors:
  - '0xFF'
  - '0xFF'
  - '0xFF'
  - '0x00'
  - '0x00'
  - '0x50'
  - '0x50'
  - '0x00'
  fog_colors:
  - '0xC0'
  - '0xC0'
  - '0xC0'
  - '0x00'
  - '0x80'
  - '0xC8'
  - '0xFF'
  - '0x00'
  music_track: '0x000F'
render:
  sky_display_lists: gLindasCastleSkyDisplayLists
  fog_display_lists: gLindasCastleFogDisplayLists
  display_list_table: gLindasCastleDisplayListTable
preview:
  world: 0
  duration: '0x01E0'
  start_waypoint: '0x43'
race:
  cpu_characters:
  - 1
  - 2
  - 0
  - 3
  cpu_board_model: 0
  cpu_snowboards:
  - - 1
    - 7
    - 3
    - 3
  - - 1
    - 8
    - 3
    - 2
  - - 1
    - 9
    - 4
    - 2
  - - 1
    - 10
    - 3
    - 3
  - - 4
    - 11
    - 4
    - 2
  - - 1
    - 12
    - 4
    - 3
  expert_snowboard: 14
  rewards:
  - 40000
  - 8000
  - 4000
overlay:
  symbol: levels_lindas_castle
  data_end: DATA_END
