key: crazy_jungle
enum: CRAZY_JUNGLE
legacy_id: 6
kind: standard
behavior: crazy_jungle
assets:
  display_lists:
    symbol: CRAZY_JUNGLE_COURSE_DISPLAY_LISTS
    decompressed_size: '0x0'
  model_resources:
    symbol: CRAZY_JUNGLE_COURSE_MODEL_RESOURCES
    decompressed_size: '0x176D0'
  track_mesh:
    symbol: CRAZY_JUNGLE_COURSE_TRACK_SECTOR_MESH
    decompressed_size: '0x2E50'
  texture_table:
    symbol: CRAZY_JUNGLE_COURSE_TEXTURE_TABLE
    decompressed_size: '0x1D68'
  gold_coins:
    symbol: CRAZY_JUNGLE_GOLD_COIN_DATA
    decompressed_size: '0x3A0'
  item_boxes:
    symbol: CRAZY_JUNGLE_ITEM_BOX_DATA
    decompressed_size: '0x100'
  scene_animation:
    symbol: CRAZY_JUNGLE_SCENE_ANIMATION_DATA
    decompressed_size: '0x340'
    legacy_slot: 1
environment:
  shortcut_position:
  - '0xC53CE61C'
  - '0xD80C3DED'
  spawn_position:
  - '0xFFF1E7C2'
  - '0x300146B4'
  - '0x30451B0B'
  yaw_offset: '0xF800'
  light_colors:
  - '0xF0'
  - '0xF0'
  - '0xA0'
  - '0x00'
  - '0x00'
  - '0x50'
  - '0x50'
  - '0x00'
  fog_colors:
  - '0x9F'
  - '0x9F'
  - '0x20'
  - '0x00'
  - '0x60'
  - '0x80'
  - '0x40'
  - '0x00'
  music_track: '0x0010'
  sky_display_lists:
  - D_80095250_95E50
  - D_80095260_95E60
  - D_80095270_95E70
preview:
  world: 1
  duration: '0x0708'
  start_waypoint: '0x52'
race:
  cpu_characters:
  - 0
  - 0
  - 4
  - 1
  cpu_board_model: 1
  cpu_snowboards:
  - - 1
    - 7
    - 5
    - 3
  - - 1
    - 8
    - 5
    - 4
  - - 1
    - 9
    - 4
    - 3
  - - 1
    - 10
    - 5
    - 4
  - - 4
    - 11
    - 4
    - 4
  - - 1
    - 12
    - 4
    - 3
  expert_snowboard: 2
  rewards:
  - 40000
  - 8000
  - 4000
overlay:
  symbol: levels_crazy_jungle
  data_end: DATA_END
