key: ice_land
enum: ICE_LAND
legacy_id: 10
kind: standard
behavior: ice_land
assets:
  display_lists:
    symbol: ICE_LAND_COURSE_DISPLAY_LISTS
    decompressed_size: '0x0'
  model_resources:
    symbol: ICE_LAND_COURSE_MODEL_RESOURCES
    decompressed_size: '0x1C050'
  track_mesh:
    symbol: ICE_LAND_COURSE_TRACK_SECTOR_MESH
    decompressed_size: '0x3BE6'
  texture_table:
    symbol: ICE_LAND_COURSE_TEXTURE_TABLE
    decompressed_size: '0x2C28'
  gold_coins:
    symbol: ICE_LAND_GOLD_COIN_DATA
    decompressed_size: '0x3E0'
  item_boxes:
    symbol: ICE_LAND_ITEM_BOX_DATA
    decompressed_size: '0x130'
  scene_animation:
    symbol: ICE_LAND_SCENE_ANIMATION_DATA
    decompressed_size: '0x280'
    legacy_slot: 8
environment:
  lift_entry_position:
  - '0x3EC583F5'
  - '0x32FA3735'
  course_start_position:
  - '0xFFFB5440'
  - '0x30053ADE'
  - '0x3040B139'
  lift_entry_yaw_offset: '0x0000'
  light_colors:
  - '0xFF'
  - '0xDF'
  - '0x0F'
  - '0x00'
  - '0x00'
  - '0x50'
  - '0x50'
  - '0x00'
  fog_colors:
  - '0x60'
  - '0x50'
  - '0x80'
  - '0x00'
  - '0x80'
  - '0x70'
  - '0xA0'
  - '0x00'
  music_track: '0x0016'
render:
  sky_display_lists: gIceLandSkyDisplayLists
  fog_display_lists: gIceLandFogDisplayLists
  display_list_table: gIceLandDisplayListTable
preview:
  world: 0
  duration: '0x04B0'
  start_waypoint: '0x23'
race:
  cpu_characters:
  - 1
  - 2
  - 0
  - 6
  cpu_board_model: 0
  cpu_snowboards:
  - - 2
    - 7
    - 7
    - 4
  - - 2
    - 8
    - 6
    - 5
  - - 2
    - 9
    - 6
    - 5
  - - 5
    - 10
    - 7
    - 5
  - - 5
    - 11
    - 6
    - 4
  - - 2
    - 12
    - 7
    - 5
  expert_snowboard: 2
  rewards:
  - 80000
  - 16000
  - 8000
overlay:
  symbol: levels_ice_land
  data_end: DATA_END
