key: snowboard_street_speed_cross
enum: SNOWBOARD_STREET_SPEED_CROSS
legacy_id: 12
kind: speed_cross
behavior: snowboard_street_speed_cross
assets:
  display_lists:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_COURSE_DISPLAY_LISTS
    decompressed_size: '0x0'
  model_resources:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_COURSE_MODEL_RESOURCES
    decompressed_size: '0x20640'
  track_mesh:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_COURSE_TRACK_SECTOR_MESH
    decompressed_size: '0x2C9E'
  texture_table:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_COURSE_TEXTURE_TABLE
    decompressed_size: '0x438'
  gold_coins:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_GOLD_COIN_DATA
    decompressed_size: '0x340'
  item_boxes:
    symbol: SNOWBOARD_STREET_SPEED_CROSS_ITEM_BOX_DATA
    decompressed_size: '0x110'
  scene_animation: null
environment:
  lift_entry_position:
  - '0x276F3DFA'
  - '0x033D7D8E'
  course_start_position:
  - '0xFFFCCAD4'
  - '0x2FFF0000'
  - '0x304E27C5'
  lift_entry_yaw_offset: '0xF800'
  light_colors:
  - '0xFF'
  - '0xFF'
  - '0xFF'
  - '0x00'
  - '0x00'
  - '0x50'
  - '0x50'
  - '0x00'
  fog_colors:
  - '0xC0'
  - '0xC0'
  - '0xC0'
  - '0x00'
  - '0x80'
  - '0xC8'
  - '0xFF'
  - '0x00'
  music_track: '0x000D'
render:
  sky_display_lists: gSnowboardStreetSpeedCrossSkyDisplayLists
  fog_display_lists: gSnowboardStreetSpeedCrossFogDisplayLists
  display_list_table: gSnowboardStreetSpeedCrossDisplayListTable
preview:
  world: 0
  duration: '0x04B0'
  start_waypoint: '0x62'
race:
  cpu_characters:
  - 1
  - 0
  - 3
  - 4
  cpu_board_model: 0
  cpu_snowboards:
  - - 1
    - 7
    - 3
    - 3
  - - 1
    - 8
    - 3
    - 4
  - - 1
    - 9
    - 4
    - 4
  - - 1
    - 10
    - 4
    - 4
  - - 4
    - 11
    - 3
    - 3
  - - 1
    - 12
    - 4
    - 3
  expert_snowboard: 2
  rewards:
  - 0
  - 0
  - 0
overlay:
  symbol: levels_snowboard_street_speed_cross
  data_end: DATA_END
