#!/usr/bin/env python3
"""Translate splat's residual data assembly (asm/data/**/*.s, GNU as / MIPS
syntax) into Mach-O PowerPC assembly for the port.

Only data directives appear in these files (no instructions): dlabel/glabel,
.word/.short/.byte/.float/.double/.space/.ascii, and a .section header.
Symbol references keep their names, prefixed with "_" for Mach-O. BSS is
emitted as zero-filled .data so labels can live inside it.

Jump tables (jtbl_*) are dropped: they point at labels inside IDO-compiled
functions and GCC makes its own.

--aliases FILE adds extra labels: each line is `NAME BASE OFFSET`, and when
BASE is defined in the file being translated, NAME is emitted OFFSET bytes
into it (the linker-script aliases into extracted data).

    asm2darwin.py --prefix _ --aliases aliases.txt --out build/x.s asm/data/x.s
"""
import argparse
import re
import sys

IDENT = re.compile(r"(?<![\w.$])([A-Za-z_][A-Za-z0-9_]*)")
DIRECTIVES = {
    ".word": (".long", 4),
    ".short": (".short", 2),
    ".half": (".short", 2),
    ".byte": (".byte", 1),
    ".float": (".single", 4),
    ".double": (".double", 8),
    ".ascii": (".ascii", None),
    ".asciz": (".asciz", None),
}
SECTIONS = {
    ".data": ".data",
    ".rodata": ".const",
    ".bss": ".data",   # zero-filled .space keeps labels addressable
    ".text": ".text",
}


def prefix_symbols(expr, prefix):
    def repl(m):
        name = m.group(1)
        if re.fullmatch(r"0[xX][0-9a-fA-F]+", name):
            return name
        return prefix + name
    return IDENT.sub(repl, expr)


def split_args(arg):
    """Split a directive argument list on commas that are not inside quotes."""
    out, cur, q = [], "", False
    for ch in arg:
        if ch == '"':
            q = not q
        if ch == "," and not q:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def string_len(arg, zero):
    s = arg.strip()
    if s.startswith('"') and s.endswith('"'):
        body = s[1:-1]
        n = 0
        i = 0
        while i < len(body):
            if body[i] == "\\":
                if i + 1 < len(body) and body[i + 1] in "01234567":
                    j = i + 1
                    while j < len(body) and j < i + 4 and body[j] in "01234567":
                        j += 1
                    i = j
                elif i + 1 < len(body) and body[i + 1] == "x":
                    j = i + 2
                    while j < len(body) and body[j] in "0123456789abcdefABCDEF":
                        j += 1
                    i = j
                else:
                    i += 2
            else:
                i += 1
            n += 1
        return n + (1 if zero else 0)
    return 0


class Translator:
    """Alias offsets are tracked relative to the current section, not to the
    label they are declared against: splat splits large arrays into several
    labels and an alias like gRaceCamerasEnd = gRaceCameras + 0x2C0 may land
    inside a later label's block."""

    def __init__(self, prefix, aliases, name, suffix=""):
        self.prefix = prefix
        self.suffix = suffix
        self.aliases = aliases     # base -> [(offset, name)]
        self.name = name
        self.out = ["; generated by port/tools/asm2darwin.py from %s" % name, "\t.data", "\t.align 4"]
        self.pos = 0               # bytes since the start of the current section
        self.pending = []          # sorted [(section offset, name)]
        self.skipping = False

    def new_section(self, directive):
        self.flush_aliases()
        if self.pending:
            sys.stderr.write("%s: aliases not placed before section change: %s\n" % (self.name, self.pending))
            self.pending = []
        self.out.append("\t" + directive)
        self.out.append("\t.align 4")
        self.pos = 0

    def label(self, sym):
        self.flush_aliases()
        self.out.append("\t.globl %s%s%s" % (self.prefix, sym, self.suffix))
        self.out.append("%s%s%s:" % (self.prefix, sym, self.suffix))
        for off, alias in self.aliases.get(sym, []):
            self.pending.append((self.pos + off, alias))
        self.pending.sort()
        self.flush_aliases()

    def flush_aliases(self):
        while self.pending and self.pending[0][0] == self.pos:
            _, alias = self.pending.pop(0)
            self.out.append("\t.globl %s%s" % (self.prefix, alias))
            self.out.append("%s%s:" % (self.prefix, alias))

    def emit_bytes(self, line, size):
        self.out.append(line)
        self.pos += size
        self.flush_aliases()

    def space(self, n):
        while self.pending and self.pending[0][0] < self.pos + n:
            gap = self.pending[0][0] - self.pos
            if gap > 0:
                self.out.append("\t.space %d" % gap)
                self.pos += gap
                n -= gap
            self.flush_aliases()
        if n > 0:
            self.out.append("\t.space %d" % n)
            self.pos += n
        self.flush_aliases()

    def line(self, raw):
        line = re.sub(r"/\*.*?\*/", "", raw).strip()
        if not line or line.startswith("#") or line.startswith("//"):
            return
        if line.startswith("enddlabel") or line.startswith("endlabel"):
            self.skipping = False
            return
        if self.skipping:
            return
        if line.startswith(".include") or line.startswith(".set "):
            return
        if line.startswith(".balign") or line.startswith(".align"):
            return  # layout inside a section is already exact; sections start aligned
        if line.startswith(".section"):
            sec = line.split()[1].rstrip(",")
            self.new_section(SECTIONS.get(sec, ".data"))
            return
        if line.startswith("nonmatching"):
            return
        if line.startswith("dlabel") or line.startswith("glabel") or line.startswith("jlabel"):
            sym = line.split()[1]
            if sym.startswith("jtbl_"):
                self.skipping = True
                return
            self.label(sym)
            return
        if line.endswith(":"):
            self.label(line[:-1])
            return
        parts = line.split(None, 1)
        d = parts[0]
        arg = parts[1] if len(parts) > 1 else ""
        if d == ".space":
            self.space(int(arg.split(",")[0], 0))
            return
        if d in DIRECTIVES:
            name, size = DIRECTIVES[d]
            if size is None:
                self.emit_bytes("\t%s %s" % (name, arg), string_len(arg, d == ".asciz"))
                return
            for it in split_args(arg):
                self.emit_bytes("\t%s %s" % (name, prefix_symbols(it, self.prefix)), size)
            return
        sys.exit("%s: unhandled line: %s" % (self.name, raw.rstrip()))

    def finish(self):
        self.flush_aliases()
        if self.pending:
            sys.stderr.write("%s: aliases beyond the end of the data: %s\n" % (self.name, self.pending))
        return "\n".join(self.out) + "\n"


def load_aliases(path):
    aliases = {}
    if not path:
        return aliases
    with open(path) as f:
        for line in f:
            parts = line.split()
            if len(parts) == 3:
                aliases.setdefault(parts[1], []).append((int(parts[2], 0), parts[0]))
    return aliases


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("--prefix", default="")
    ap.add_argument("--aliases")
    ap.add_argument("--suffix", default="", help="append to every label (twin naming)")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    t = Translator(args.prefix, load_aliases(args.aliases), args.src, args.suffix)
    with open(args.src) as f:
        for raw in f:
            t.line(raw)
    with open(args.out, "w") as f:
        f.write(t.finish())


if __name__ == "__main__":
    main()
