#!/usr/bin/env python3
"""Emit absolute symbols for the N64 build's address-valued linker symbols so
the port's native link resolves `&FOO_ROM_START`, `&BAR_VRAM`, `D_2000000`...
to the same numeric values the game expects.

Included: every *_ROM_START / *_ROM_END / *_VRAM / *_VRAM_END, plus the
assignments in linker_scripts/game_syms.ld whose right-hand side is built only
from those (segment addresses, fixed physical addresses). Assignments that
alias into C data (gFoo = gBar + 0x3F) are reported and left to port_aliases.

    gen_rom_syms.py build/snowboardkids.map --ld linker_scripts/game_syms.ld --prefix _ --out rom_syms.s
"""
import argparse
import re
import sys

MAP_RE = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")
SYM_RE = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*$")
LD_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);")
IDENT_RE = re.compile(r"(?<![0-9A-Za-z_])[A-Za-z_][A-Za-z0-9_]*")
ADDR_SUFFIX = ("_ROM_START", "_ROM_END", "_VRAM", "_VRAM_END")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map")
    ap.add_argument("--ld", action="append", default=[], help="linker script(s) with extra absolute assignments")
    ap.add_argument("--fixed", action="append", default=[], help="plain symbol to pin at its N64 address (emulated RDRAM)")
    ap.add_argument("--extra-abs", action="append", default=[], help="file of \"NAME 0xADDR\" lines to treat as absolute")
    ap.add_argument("--skip", action="append", default=[], help="names never to emit (defined by the port)")
    ap.add_argument("--skip-file", action="append", default=[], help="file of names never to emit (one per line)")
    ap.add_argument("--prefix", default="")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    values = {}
    plain = {}
    with open(args.map) as f:
        for line in f:
            m = MAP_RE.match(line)
            if m:
                values[m.group(2)] = int(m.group(1), 16)
                continue
            m = SYM_RE.match(line)
            if m:
                plain[m.group(2)] = int(m.group(1), 16)

    absolute = {n: v for n, v in values.items() if n.endswith(ADDR_SUFFIX)}
    if not absolute:
        sys.exit("no ROM/VRAM symbols found in %s (run the N64 build first)" % args.map)

    for name in args.fixed:
        if name not in plain:
            sys.exit("fixed symbol %s not found in the map" % name)
        absolute[name] = plain[name]

    seed_only = set()  # known absolutes defined elsewhere (pins.s): resolve with, never emit
    for path in args.extra_abs:
        with open(path) as f:
            for line in f:
                parts = line.split()
                if len(parts) >= 2:
                    absolute[parts[0]] = int(parts[1], 0)
                    seed_only.add(parts[0])

    ld_assign = {}
    for path in args.ld:
        with open(path) as f:
            for line in f:
                m = LD_RE.match(line)
                if m:
                    ld_assign[m.group(1)] = m.group(2)

    skipped = []
    changed = True
    while changed:
        changed = False
        for name, rhs in ld_assign.items():
            if name in absolute or name not in values:
                continue
            idents = [i for i in IDENT_RE.findall(rhs) if not re.fullmatch(r"0[xX][0-9a-fA-F]+", i)]
            if all(i in absolute for i in idents):
                absolute[name] = values[name]
                changed = True
        for name, rhs in ld_assign.items():
            if name not in absolute and re.fullmatch(r"\s*(0[xX][0-9a-fA-F]+|\d+)\s*", rhs):
                absolute[name] = int(rhs.strip(), 0)  # numeric, even if absent from the map
                changed = True
    for name in ld_assign:
        if name not in absolute:
            skipped.append(name)

    for path in args.skip_file:
        with open(path) as f:
            for line in f:
                absolute.pop(line.strip(), None)
    for name in list(args.skip) + list(seed_only):
        absolute.pop(name, None)
    with open(args.out, "w") as out:
        out.write("; generated by port/tools/gen_rom_syms.py from %s: %d symbols\n" % (args.map, len(absolute)))
        for name in sorted(absolute):
            out.write("\t.globl %s%s\n%s%s = 0x%08X\n" % (args.prefix, name, args.prefix, name, absolute[name]))
    print("rom_syms: %d absolute symbols -> %s" % (len(absolute), args.out))
    if skipped:
        print("rom_syms: %d linker aliases into C data left for port_aliases: %s" % (len(skipped), " ".join(sorted(skipped))))


if __name__ == "__main__":
    main()
