#!/usr/bin/env python3
"""Embed resources/launcher-logo.png as src/ui/ui_logo.h: 512x288 RGBA8, drawn by
sbk_ui_logo() from a 512x512 power-of-two texture (Radeon 9000: no NPOT)."""
import os, sys
from PIL import Image
here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "resources", "launcher-logo.png")
dst = os.path.join(here, "..", "src", "ui", "ui_logo.h")
W, H = 512, 288
im = Image.open(src).convert("RGBA")
im = im.resize((W, H), Image.LANCZOS)
px = im.tobytes()
with open(dst, "w") as f:
    f.write("/* generated by tools/gen_logo.py from resources/launcher-logo.png; do not edit */\n")
    f.write("#define SBK_UI_LOGO_W %d\n#define SBK_UI_LOGO_H %d\n" % (W, H))
    f.write("static const unsigned char sbk_ui_logo_rgba[%d] = {\n" % len(px))
    for i in range(0, len(px), 32):
        f.write(",".join(str(b) for b in px[i:i + 32]) + ",\n")
    f.write("};\n")
print("wrote", dst, len(px), "bytes")
