#!/usr/bin/env python3
"""Pin every named global of the game at its N64 address.

The game's data layout is load-bearing (arrays walked until the next global,
pointers baked into replay data, `ptr + 0x80000000` physical-address tricks),
so the port keeps the N64 layout: every data/rodata/bss symbol of the main
segment becomes an absolute symbol inside the emulated RDRAM, the C (and
translated-asm) definitions are renamed to `NAME__sbk_unpinned` "twins" by the
mirror step, and at startup the twins' initial values are copied to the pinned
addresses (pin_table.c). BSS needs nothing: RDRAM starts zeroed.

Inputs: the N64 link map, optionally `mips64-elf-nm -S` output for sizes, and
the list of objects the port actually compiles (whose twins exist).

Outputs:
  --pins-s      assembly defining the absolute symbols
  --pins-txt    "NAME 0xADDR" lines (fed to gen_rom_syms.py and mirror_src.py)
  --table-c     C file with the startup copy table
"""
import argparse
import re
import sys

OBJ_RE = re.compile(r"^ \.(\w+)\s+0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\s+(\S+\.o)\s*$")
SYM_RE = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*$")
ASSIGN_RE = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=")
RDRAM_LO, RDRAM_HI = 0x80000000, 0x80400000


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("map")
    ap.add_argument("--nm", help="output of mips64-elf-nm -S on the N64 ELF")
    ap.add_argument("--objs", required=True, help="file listing compiled/translated objects (build/... .o), one per line")
    ap.add_argument("--pin-hi", default=None, help="do not pin at or above this address")
    ap.add_argument("--pin-skip", action="append", default=[], help="LO:HI address range never to pin (overlapping overlay regions)")
    ap.add_argument("--prefix", default="")
    ap.add_argument("--suffix", default="__sbk_unpinned")
    ap.add_argument("--pins-s", required=True)
    ap.add_argument("--pins-txt", required=True)
    ap.add_argument("--native-txt", help="write every symbol owned by a compiled object here (gen_rom_syms --skip-file)")
    ap.add_argument("--table-c", required=True)
    args = ap.parse_args()

    with open(args.objs) as f:
        twins_available = set(line.strip() for line in f if line.strip())

    sizes = {}
    if args.nm:
        with open(args.nm) as f:
            for line in f:
                parts = line.split()
                if len(parts) == 4:
                    sizes[parts[3]] = int(parts[1], 16)

    data_start = data_end = rodata_end = None
    entries = []  # (addr, name, section, obj)
    cur = None
    with open(args.map) as f:
        for line in f:
            m = ASSIGN_RE.match(line)
            if m:
                if m.group(2) == "main_DATA_START":
                    data_start = int(m.group(1), 16)
                elif m.group(2) == "main_DATA_END":
                    data_end = int(m.group(1), 16)
                elif m.group(2) == "main_RODATA_END":
                    rodata_end = int(m.group(1), 16)
                continue
            m = OBJ_RE.match(line)
            if m:
                cur = (m.group(1), int(m.group(2), 16), int(m.group(3), 16), m.group(4))
                continue
            m = SYM_RE.match(line)
            if m and cur is not None:
                addr = int(m.group(1), 16)
                sec, sec_addr, sec_size, obj = cur
                if sec_addr <= addr < sec_addr + max(sec_size, 1) or (sec_size == 0 and addr == sec_addr):
                    entries.append((addr, m.group(2), sec, sec_addr + sec_size, obj))
    if data_start is None or data_end is None or rodata_end is None:
        sys.exit("gen_pins: main_DATA_START/END or main_RODATA_END not found in the map")

    hi = int(args.pin_hi, 0) if args.pin_hi else RDRAM_HI
    # Address ranges shared by several overlays (a level's globals sit at the
    # same VRAM as every other level's) cannot be pinned: those stay native.
    skip = []
    for spec in args.pin_skip:
        lo_s, hi_s = spec.split(":")
        skip.append((int(lo_s, 0), int(hi_s, 0)))
    def blocked(a):
        return any(lo <= a < h for lo, h in skip)
    pins = [e for e in entries if RDRAM_LO <= e[0] < min(RDRAM_HI, hi) and e[0] >= data_start
            and e[2] != "text" and not blocked(e[0])]
    pins.sort()
    names = set()
    unique = []
    for e in pins:
        if e[1] not in names:
            names.add(e[1])
            unique.append(e)
    pins = unique

    with open(args.pins_s, "w") as out:
        out.write("; generated by port/tools/gen_pins.py: %d globals pinned at their N64 addresses\n" % len(pins))
        for addr, name, sec, sec_end, obj in pins:
            out.write("\t.globl %s%s\n%s%s = 0x%08X\n" % (args.prefix, name, args.prefix, name, addr))

    with open(args.pins_txt, "w") as out:
        for addr, name, sec, sec_end, obj in pins:
            out.write("%s 0x%08X %s\n" % (name, addr, obj))

    if args.native_txt:
        # Symbols the port compiles itself (including overlay globals that are
        # never pinned): gen_rom_syms must not turn any of them into an
        # absolute, or the native definition and the absolute collide.
        with open(args.native_txt, "w") as out:
            seen = set()
            for addr, name, sec, sec_end, obj in entries:
                if obj in twins_available and name not in seen:
                    seen.add(name)
                    out.write("%s\n" % name)

    copied = 0
    with open(args.table_c, "w") as out:
        out.write("/* generated by port/tools/gen_pins.py: initial values of pinned globals */\n")
        out.write("#include <stddef.h>\n#include <stdint.h>\n#include \"ultra/sbk_pins.h\"\n\n")
        decls = []
        rows = []
        for i, (addr, name, sec, sec_end, obj) in enumerate(pins):
            if sec == "bss" or addr >= rodata_end and sec not in ("data", "rodata"):
                continue  # bss: zero already
            if obj not in twins_available:
                continue  # no native twin (libultra data the port replaces)
            # Cap: the space up to the next pinned symbol (or the section end).
            # C twins publish their real sizeof (mirror_src.py); the copy takes
            # the smaller of the two. Translated asm twins keep the ELF size,
            # which is exact for them. The ELF size alone is NOT trusted for C
            # data: IDO reports only the initialised prefix of string tables.
            nxt = pins[i + 1][0] if i + 1 < len(pins) else sec_end
            cap = min(nxt, sec_end) - addr
            if cap <= 0:
                cap = sizes.get(name, 0)
            if cap <= 0 or cap > (1 << 20):
                continue
            from_asm = obj.startswith("build/asm/")
            if from_asm:
                size = sizes.get(name, 0) or cap
                decls.append("extern const char %s%s[];\n" % (name, args.suffix))
                rows.append("    { %s%s, 0x%08Xu, %u, NULL },\n" % (name, args.suffix, addr, min(size, cap)))
            else:
                decls.append("extern const char %s%s[];\nextern const unsigned long %s__sbk_size;\n" % (name, args.suffix, name))
                rows.append("    { %s%s, 0x%08Xu, %u, &%s__sbk_size },\n" % (name, args.suffix, addr, cap, name))
            copied += 1
        out.writelines(decls)
        out.write("\nconst struct sbk_pin sbk_pin_table[] = {\n")
        out.writelines(rows)
        out.write("    { NULL, 0, 0, NULL }\n};\n")
    print("pins: %d symbols pinned, %d initialised from twins -> %s" % (len(pins), copied, args.table_c))


if __name__ == "__main__":
    main()
