#!/usr/bin/env python3
"""Embed hand-drawn box fronts, if there are any, as src/ui/ui_box.h.

The launcher composes each game's box front from that game's own title logo,
pulled out of the cartridge at run time.  If you would rather draw the front
yourself, drop a picture in (any size, any aspect -- it is fitted to the
256x358 front of the box):

    port/resources/box-sbk1.png
    port/resources/box-sbk2.png

then run this and rebuild.  Either or both; a game with no file keeps the
generated front.  Running it with neither present writes the empty header,
which is what is checked in, so the build never depends on a file that is not
in the repository.
"""
import os
import sys

W, H = 256, 358          # SBK_BOX_FRONT_W x SBK_BOX_FRONT_H

here = os.path.dirname(os.path.abspath(__file__))
res = os.path.join(here, "..", "resources")
dst = os.path.join(here, "..", "src", "ui", "ui_box.h")

GAMES = [("sbk1", "SBK1"), ("sbk2", "SBK2")]


def load(name):
    path = os.path.join(res, "box-%s.png" % name)
    if not os.path.exists(path):
        return None
    from PIL import Image
    im = Image.open(path).convert("RGBA")
    # cover the front: scale to fill, then centre-crop, so an image of any
    # aspect fills the box rather than being letterboxed onto it
    sw, sh = im.size
    scale = max(W / float(sw), H / float(sh))
    im = im.resize((max(1, int(sw * scale + 0.5)), max(1, int(sh * scale + 0.5))), Image.LANCZOS)
    sw, sh = im.size
    im = im.crop(((sw - W) // 2, (sh - H) // 2, (sw - W) // 2 + W, (sh - H) // 2 + H))
    return im.tobytes()


def main():
    out = ["/* generated by tools/gen_box.py; do not edit */",
           "#ifndef SBK_UI_BOX_H",
           "#define SBK_UI_BOX_H",
           "",
           "/* Hand-drawn box fronts, %dx%d RGBA8.  A game with no picture here" % (W, H),
           " * gets one composed from its own title logo instead. */",
           ""]
    found = []
    for name, tag in GAMES:
        px = load(name)
        if px is None:
            continue
        found.append(name)
        out.append("#define SBK_BOX_HAVE_%s 1" % tag)
        out.append("static const unsigned char sbk_box_%s_rgba[%d] = {" % (name, len(px)))
        for i in range(0, len(px), 32):
            out.append(",".join(str(b) for b in px[i:i + 32]) + ",")
        out.append("};")
        out.append("")
    out.append("#endif")
    with open(dst, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s (%s)" % (dst, ", ".join(found) if found else "no box fronts present"))


if __name__ == "__main__":
    sys.exit(main())
